### ISSUE TITLE
ExportToDatabase and/or Path Mapping issues with DCP prevent batch data aggregation on AWS RDS - Workaround Added in Comments

### ISSUE THREAD

**Issue by mamrrmam** [DistributedScience/Distributed-CellProfiler#129]
Hello DCP community,

I am relatively new to DCP, and have got things running OK but noticed some weird behaviour in my cloud watch logs re: DCP core behaviour.

For starters, I am running DCP (Docker hub tag: cellprofiler/distributed-cellprofiler:2.0.0_4.2.1) on AWS using the ECS-optimized LINUX AMI as suggested in the wiki. I am attempting to write the data to a MYSQL database using ExportToDatabase. I have it set up on AWS RDS which so far has been feasible but with some weird write behaviour. The rest of things are running as expected. 

CP does not like to append new data to MYSQL and prefers to overwrite - this is all fairly well documented piecemeal across various issues here and on some forums. 

Essentially, my problem boils down to the following -
(1) if I use batchfiles to load the data, DCP does not seem to point at the correct directories
(2) if I use LoadData to load the data, it points at the correct directories but overwrites my database on each run
(3) if I use a combination or batchfiles with load data and use the jobfile.json to point DCP to my image-set-listing.csv in {data:} and  to batch_file.h5 in {pipeline}, the result is similar to that in (2), see below for details. NB. for this, I have edited the image-set-listing to point at the correct directories in excel before running the job.

So, lets get to it.

**Option 1: Batchfiles -** at the end of the pipeline, I create a batchfile to run the job file (so in my jobfile.json, both data and pipeline both point to the batchfile.h5). This causes the error:

**error**
````
INFO:__main__:Error detected during run of module NamesAndTypes
Traceback: most recent call last

  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/pipeline/_pipeline.py", line 976, in run_with_yield
  | 2022-04-18T20:24:50.408-04:00 | self.run_module(module, workspace)
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/pipeline/_pipeline.py", line 1298, in run_module
  | 2022-04-18T20:24:50.408-04:00 | module.run(workspace)
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/modules/namesandtypes.py", line 1940, in run
  | 2022-04-18T20:24:50.408-04:00 | self.add_image_provider(
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/modules/namesandtypes.py", line 2003, in add_image_provider
  | 2022-04-18T20:24:50.408-04:00 | self.add_simple_image(
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/modules/namesandtypes.py", line 2062, in add_simple_image
  | 2022-04-18T20:24:50.408-04:00 | self.add_provider_measurements(provider, m, "Image")
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/modules/namesandtypes.py", line 2076, in add_provider_measurements
  | 2022-04-18T20:24:50.408-04:00 | img = provider.provide_image(m)
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/image/abstract_image/file/url/_monochrome_image.py", line 33, in provide_image
  | 2022-04-18T20:24:50.408-04:00 | image = URLImage.provide_image(self, image_set)
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/image/abstract_image/file/_file_image.py", line 327, in provide_image
  | 2022-04-18T20:24:50.408-04:00 | self.__set_image()
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/image/abstract_image/file/_file_image.py", line 264, in __set_image
  | 2022-04-18T20:24:50.408-04:00 | self.cache_file()
  | 2022-04-18T20:24:50.408-04:00 | File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/image/abstract_image/file/_file_image.py", line 159, in cache_file
  | 2022-04-18T20:24:50.408-04:00 | raise IOError(
  | 2022-04-18T20:24:50.408-04:00 | OSError: Test for access to directory failed. **Directory: ///E:/XYZ/XYZ/XYZ...**
````

I have changed my directory here to XYZ/XYZ but as you can see, the batchfile does not properly change the path because DCP is testing for access to a directory on my local machine - I have included a path mapping to my files on S3 (directories that work in the LoadData context, more on this in a minute), but it is not registering in the run. On my local machine, I am running CP 4.2.1 on windows 11, making me thing there is an issue with the path mapping code in this version or some other issue generated by running it in my local environment. 

**Option 2: LoadData -** The other option is using LoadData. For this, DCP likes to continually overwrite the MYSQL database on each run, so I run the CreateBatchFiles module at the end of the pipeline on my local machine once with ExportToDatabase set to Overwrite Data and Schema such that the tables are instantiated on my MYSQL_database. Then, I delete the CreateBatchFiles module, reset the Overwrite settings in ExportToDatabase, save and upload my pipeline to S3. Here, I use the jobfile to point to a *manually edited version of the image-set-list.csv* in data and for pipeline I point directly at this pipeline.cppipe. I have tried running this with the Overwrite set to Data and Schema and this continually overwrites the database each time an instance runs a job. If you set it to overwrite "Data" only, the following error occurs: 

"Detected error during run of export to database module: Feature ExportToDb_Images for Experiment does not exist."

The error is reproduced below for (3). It seems that the error is coming from within the ExportToDatabase module code, wherein it references the h5 dictionary repeatedly. Interestingly, Images and Experiment are both "group" or handle elements of the batch file, so most likely this is failing because it is expecting a batch file but does not have one. However, as you can see, when I provide the batch file it also fails.

**Option 3: LoadData/Batchfile Combo -** The third option is to use the batchfile to take advantage of the MYSQL write behaviour using this system, but point DCP at the correct directories. This would ideally overcome the limitations of both of issues (1) and (2); however, pointing DCP at a batch file in any context seems to create the same issue that fails in (2). This is also the case if I include the LoadData module in the pipeline but run the jobfile pointed at the batchfile for both {Pipeline:} and {Data:}.

````
INFO:__main__:Error detected during run of module ExportToDatabase
Traceback (most recent call last):
  | 2022-04-20T00:07:20.417-04:00CopyINFO:__main__:  File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/pipeline/_pipeline.py", line 976, in run_with_yield | INFO:__main__: File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/pipeline/_pipeline.py", line 976, in run_with_yield
  | 2022-04-20T00:07:20.417-04:00 | INFO:__main__: self.run_module(module, workspace)
  | 2022-04-20T00:07:20.417-04:00 | INFO:__main__: File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/pipeline/_pipeline.py", line 1298, in run_module
  | 2022-04-20T00:07:20.417-04:00 | INFO:__main__: module.run(workspace)
  | 2022-04-20T00:07:20.417-04:00 | INFO:__main__: File "/usr/local/lib/python3.8/dist-packages/cellprofiler/modules/exporttodatabase.py", line 2585, in run
  | 2022-04-20T00:07:20.417-04:00 | INFO:__main__: self.record_image_channels(workspace)
  | 2022-04-20T00:07:20.417-04:00 | INFO:__main__: File "/usr/local/lib/python3.8/dist-packages/cellprofiler/modules/exporttodatabase.py", line 4773, in record_image_channels
  | 2022-04-20T00:07:20.418-04:00 | INFO:__main__: image_list = workspace.measurements.get_experiment_measurement("ExportToDb_Images")
  | 2022-04-20T00:07:20.418-04:00 | INFO:__main__: File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/measurement/_measurements.py", line 962, in get_experiment_measurement
  | 2022-04-20T00:07:20.418-04:00 | INFO:__main__: result = self.get_measurement(EXPERIMENT, feature_name)
  | 2022-04-20T00:07:20.418-04:00 | INFO:__main__: File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/measurement/_measurements.py", line 837, in get_measurement
  | 2022-04-20T00:07:20.418-04:00 | INFO:__main__: result = self.hdf5_dict[EXPERIMENT, feature_name, 0]
  | 2022-04-20T00:07:20.418-04:00 | INFO:__main__: File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/utilities/hdf5_dict.py", line 417, in __getitem__
  | 2022-04-20T00:07:20.418-04:00 | INFO:__main__: result = self[object_name, feature_name, [num_idx]]
  | 2022-04-20T00:07:20.418-04:00 | INFO:__main__: File "/usr/local/lib/python3.8/dist-packages/cellprofiler_core/utilities/hdf5_dict.py", line 422, in __getitem__
  | 2022-04-20T00:07:20.418-04:00CopyINFO:__main__:    assert feature_exists, "Feature {} for {} does not exist".format( | INFO:__main__: assert feature_exists, "Feature {} for {} does not exist".format(
  | 2022-04-20T00:07:20.419-04:00 | INFO:__main__:AssertionError: Feature ExportToDb_Images for Experiment does not exist
````

**Conclusions**

I have done a lot of poking around in the Batch_file.h5 as well as having many different permutations of Batch_file settings, JobFile submissions, etc. The NamesAndTypes - Directory error is perplexing because I have no idea where the directory to my local machine is being submitted to DCP from. I have gone as far as manually changing all filepaths, url's etc. in the batch file to match my cluster, but the error persists. It is hidden somewhere else, clearly, and I have no idea where.

When I add the filepaths by .csv, clearly the pipeline gets much further in (to ExportToDatabase); however, again an error is thrown. Interestingly, ExportToDb_Images is identical in the batchfile produced when the files are added with LoadData module versus when they are added thru the GUI so I don't have any clue why this is failing. Perhaps there is an additional component required in the .csv that is not there.

**Recommendations** 

For any CP/DCP experts, if you have any comments or advice with next steps for getting my data output to MYSQL without overwriting on each run, please reply.

Finally, thanks to the CP/DCP team for providing a great software and maintaining such a helpful community here.

All the best,

mamrrmam

**Comment by mamrrmam** [comment]
**Update on Using Edited Batchfiles**

Ok, so now I've attempted a run with edited batch_file.h5 and the directory error is still happening. Since I have edited the Image/FilePath and Image/URL it is most likely living within Pipeline/Pipeline so now I am going to go have a look at that. 

More on this soon.

**Comment by mamrrmam** [comment]
**Update Two on Using Edited Batchfiles**

Ok, on further review of Batch_data.h5, there are references in the Pipeline_Pipeline data to the directory referenced in my Cloud Logs error.

From above, the ultimate error was:
````
2022-04-19T14:57:47.736-04:00 OSError: Test for access to directory failed. Directory: ///E:/XYZ/XYZ/XYZ/rest_of_path
`````

I pulled the structure data from pipeline_pipeline in my case using:
````
> test&'/Measurements/2022-04-18-23-04-05/Experiment/Pipeline_Pipeline/data'
HDF5 DATASET 
        name /Measurements/2022-04-18-23-04-05/Experiment/Pipeline_Pipeline/data
    filename 
        type H5T_STRING
        rank 1
        size 3
     maxsize 18446744073709551616
````

Initially this looked like another array to me, given that the other data were stored as arrays and this has size: 3. I ported this into a named variable and copy pasted each of the indices from the R console into word so I could search for my error fragment. Overall, this data appears to be stored as an array of tab separated values corresponding to pipeline settings. I am not posting it here because it is long and ultimately of little use.

````
pipeline <- as.array(test$'/Measurements/2022-04-18-23-04-05/Experiment/Pipeline_Pipeline/data')
pipeline[1]
pipeline[2]
pipeline[3] #done seperately because these are too long individually for the console to keep all the output
````

I also tested the indices for equivalence and it was at this point that I realized that h5 most likely stores three separate and possibly different copies of the pipeline because many of the h5 groups corresponding to images or channels have arrayed indexes of 3 - they probably map to each other. I assume it works this way so that the images can be handled separately in a given run although I could be wrong about my suspicions. Not my circus, not my monkeys. More importantly:

````
> pipeline[1] == pipeline[2]
[1] TRUE
> pipeline[1] == pipeline[3]
[1] FALSE
````

Interestingly, when I CTRL+F'd my way thru the console dump in my word file, I noticed that all pipeline indices have the same pipeline entry towards the end marked as *hidden*.
````
Hidden- default input folder at time of save:\\\E:\\XYZ\\XYZ\\XYZ\\rest_of_path ...
````
What was odd was that for pipeline[1] and pipeline[2], the entry uses backslashes as above, but for pipeline[3] it looked like this
````
Hidden- default input folder at time of save:///E:/XYZ/XYZ/XYZ/rest_of_path ...
````
I am not sure, but perhaps the reason my path mapping was not working initially was because I had set LCP to look for E:\XYZ\XYZ, but pipeline[3] is reading E:/XYZ/XYZ so the path is not swapped when DCP interprets the batch files. Maybe there is no particular issue with DCP, and the CreateBatchFiles module in LCP is the culprit after all.

So, I re-ran LCP with two path mappings this time:
```` 
Local Root Path    : E:\XYZ\XYZ
Cluster Root Path : /home/ubuntu/bucket
and
Local Root Path    : E:/XYZ/XYZ
Cluster Root Path : /home/ubuntu/bucket
````
Interestingly, now pipeline[1] and [2] read like this:
````
Hidden- default input folder at time of save:E:\\XYZ\\XYZ\\rest of path\n    Hidden- revision number:0\n    Hidden- from old matlab:No\n    Local root path:E:\\XYZ\\XYZ\n    Cluster root path:/home/ubuntu/bucket\n    Local root path:E:/XYZ/XYZ\n    Cluster root path:/home/ubuntu/bucket\n"
````
Whereas, pipeline[3] reads like this:
````
Hidden- default input folder at time of save:/home/ubuntu/bucket/rest_of_path\n    Hidden- revision number:421\n    Hidden- from old matlab:No\n    Local root path:E:\\XYZ\\XYZ\n    Cluster root path:/home/ubuntu/bucket\n    Local root path:E:/XYZ/XYZ\n    Cluster root path:/home/ubuntu/bucket\n"
````
So, I have surmised that something odd is going on with LCP during pathmapping in CreateBatchFiles. I wonder if it is possible that because I am running LCP on windows, I have to submit the \\ to CreateBatchFiles in the local root path so that whatever substring function can find it. Based on the error in the cloud logs, DCP is using this 'default input folder' to try to get access to the images in question. Why I do not know, perhaps there is some upstream error which causes this, only time will tell. At this point, I am thinking the DCP run is fixable if I can get these entries sorted out.

For one last hurrah with LCP, I tried this:
```` 
Local Root Path    : E:\\XYZ\\XYZ
Cluster Root Path : /home/ubuntu/bucket
and
Local Root Path    : E:/XYZ/XYZ
Cluster Root Path : /home/ubuntu/bucket
````

Oddly, now all three pipeline indices show the local pathmapping as unchanged, with the additional settings saved for the re-mapping in DCP.
````
pipeline[1] and [2] look like this:
Hidden- default input folder at time of save:E:\\XYZ\\XYZ\\rest_of_path\n    Hidden- revision number:0\n    Hidden- from old matlab:No\n    Local root path:E:\\\\XYZ\\\\XYZ\n    Cluster root path:/home/ubuntu/bucket\n    Local root path:E:/XYZ/XYZ\n    Cluster root path:/home/ubuntu/bucket\n"
pipeline[3] looks like this:
Hidden- default input folder at time of save:E:/XYZ/XYZ/rest_of_path\n    Hidden- revision number:421\n    Hidden- from old matlab:No\n    Local root path:E:\\\\XYZ\\\\XYZ\n    Cluster root path:/home/ubuntu/bucket\n    Local root path:E:/XYZ/XYZ\n    Cluster root path:/home/ubuntu/bucket\n"
````
No I am even more convinced something is off in CreateBatchFiles because I didn't change the second path mapping and the output was different. Unless I am way off base about how this works, that seems suspicious to me. Anyways, I can manually update these entries in R. So now let's assume there is an error in Pipeline_Pipeline and have a look at User_Pipeline.

````
> test&'/Measurements/2022-04-18-23-04-05/Experiment/Pipeline_UserPipeline/data'
HDF5 DATASET 
        name /Measurements/2022-04-18-23-04-05/Experiment/Pipeline_UserPipeline/data
    filename 
        type H5T_STRING
        rank 1
        size 1
     maxsize 18446744073709551616
````

User_Pipeline seems to be a single entry which bodes well for simplicity. In the original batch_file, in the final part of User_Pipeline, it reads:
````
Hidden- in batch mode:No\n    Hidden- in distributed mode:No\n    Hidden- default input folder at time of save:E:\\XYZ\\XYZ\\rest_of_path\n    Hidden- revision number:0\n    Hidden- from old matlab:No\n"
````
This appears to use the same backslash formatting as pipeline[1] and [2] above, so is unlikely to be the culprit because it doesn't match the forward slash formatting of my cloud watch error (unless there is some interpretation in DCP that is changing the slashes around befor it throws the error of course).

**Conclusions**
What a heck of a mess. CreateBatchFiles appears to be CreativeBatchFiles. I will manually edit my first batch_file at the Pipeline_Pipeline[3] entry where it includes the forward slashes and give it a run on DCP.

Back soon to let you know how it goes.

mamrrmam




</body>
</html>

**Comment by mamrrmam** [comment]
**Update Three on Editing Batchfiles**

Ok, so now I've manually edited the batchfile. Basically, I edited only the entry which matched my error first (ie. forward slashes, 'pipeline[3]' *see above*). When I ran this in DCP it threw the same error. Next I tried editing the other entries in Pipeline_Pipeline to change them to my S3 bucket path. This also threw the same error. Finally, I additionally edited Pipeline_UserPipeline. Same error. I'm stuck. Will come back to this tomorrow.

**Comment by mamrrmam** [comment]
Hello, for anyone who has arrived here, I have implemented a work-around based on using SQLite with DCP. Hope this can help you save hours and hours of troubleshooting time. In short, the problem with SQLite is that DCP will output a single database for each image processed on an instance. So obviously, MySQL output would be preferable but I could never arrive at a working implementation of that strategy for DCP.

Therefore, I have written code to handle merging and post-processing for large numbers (up to thousands) of databases outputted using either "SingleObjectTable" or "SingleObjectView" from the ExportToDatabase module.

See here: https://github.com/mamrrmam/SQLite-MegaMerge-for-Distributed-CellProfiler 

and here for the general merge code without the CP bells and whistles: https://github.com/mamrrmam/SQLite-Mega-Merge

The code is not generalized and can take a while to run with particularly large datasets but it does the job.

Thanks to the CP/DCP community.

**Comment by ErinWeisbart** [comment]
Thanks so much for sharing your workaround!
We have added "Support for RDS" as a [requested enhancement to CellProfiler](https://github.com/CellProfiler/CellProfiler/issues/4650) and when that change is made there we will ensure it is compatible with DCP.
