### ISSUE TITLE
Look into new role creation

### ISSUE THREAD

**Issue by bethac07** [DistributedScience/Distributed-CellProfiler#131]
AWS has changed their role creation thing AGAIN, so setup is now harder than it was. They do now offer "use cases" though, one of which is EC2 - Fleet, which looks like it would PROBABLY work for our purposes. If so, we can update the instructions to just do that, otherwise, we should write up the new instructions (picking "Custom trust policy", setting the Principal to `"Service": "spotfleet.amazonaws.com"`, add the SpotFleetTaggingRole policy, and name it)

**Comment by ErinWeisbart** [comment]
I think this was handled in https://github.com/DistributedScience/Distributed-CellProfiler/pull/135
But please let me know if I missing something.

> In the current interface, it's easiest to click "Create role", select "EC2" from the main service list, then select "EC2- Spot Fleet Tagging".

**Comment by ErinWeisbart** [comment]
It has been over a year of thinking that this was handled and no reports otherwise so I'm going to close this issue.
