### ISSUE TITLE
Update cp-worker for readability?

### ISSUE THREAD

**Issue by ErinWeisbart** [DistributedScience/Distributed-CellProfiler#141]
@bethac07 How do you feel about me re-writing a couple parts of DCP to increase readability?
Basically, I'd love to re-write to use f-strings for the [CellProfiler command ](https://github.com/DistributedScience/Distributed-CellProfiler/blob/9917a0669cdde4120dde345188741cf58cb59bde/worker/cp-worker.py#L227) so it's easier to read/understand.
It'd be nice to bring this part of the code into the land of Python3, but I want to make sure I'm not missing a reason not to do so.

**Comment by bethac07** [comment]
I feel 🎉 about it. Was not not-done, just not-done-yet :)

**Comment by ErinWeisbart** [comment]
Fixed in 9898cce67f89d3b3773f540a704b45cce1bbc6e5
