### ISSUE TITLE
Add citation info

### ISSUE THREAD

**Issue by ErinWeisbart** [DistributedScience/Distributed-CellProfiler#149]
Add CITATION.cff to repo as described:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

Add citation info in documentation.

**Comment by ErinWeisbart** [comment]
@bethac07 do we want list preferred citation as DS paper as it is the most recent paper to address DCP? or keep it as the CP3 paper?

**Comment by bethac07** [comment]
Why not both . gif

**Comment by ErinWeisbart** [comment]
My understanding is that in a `CITATION.cff` you can only put one `preferred-citation`.
If that is true, it looks like a workaround is to list a single `preferred-citation` and list the second citation as a `reference` and have the message indicate that users should cite both the `preferred-citation` and `reference`.

(Obviously in our documentation we can easily list both)

**Comment by bethac07** [comment]
Cool, then let's stick with McQuin for the preferred citation on this one, since it is where this software was originally cited, and do as you suggest re: the other as a reference.
