### ISSUE TITLE
Your spot fleet request is causing an error and is now being cancelled

### ISSUE THREAD

**Issue by sooheon** [DistributedScience/Distributed-CellProfiler#151]
I followed these directions to manually input launch specs (AMI id and snapshot id) for a different region (ap-northeast-2): https://distributedscience.github.io/Distributed-CellProfiler/step_3_start_cluster.html#to-run-in-a-region-where-a-spot-fleet-config-isn-t-available-or-is-out-of-date

Getting following error:

```
Request in process. Wait until your machines are available in the cluster.
SpotFleetRequestId [...]
Updating service
Service updated.
.
.
Your spot fleet request is causing an error and is now being cancelled.  Please check your configuration and try again
spotFleetRequestConfigurationInvalid : c5.xlarge, ami-096981b2599d2d99b, Linux/UNIX: Value
```

The `Linux/UNIX: Value` looks strange to me, almost like a Key/Value in some config hasn't been set properly, but I don't see anything like it in the files I've touched.

**Comment by sooheon** [comment]
Resolved!

Dug around in the AWS EC2 > Spot requests > History, a previous log msg had a more detailed error message (one of the ARNs were wrong). Apparently there is a `launchSpecTemporarilyBlacklisted` status that can blacklist launch requests that keep erroring out!

**Comment by Gabcomolet** [comment]
I have the same issue, could you explain how you solved this? 
Thank you
