### ISSUE TITLE
Print easier to read memory used metrics?

### ISSUE THREAD

**Issue by ErinWeisbart** [DistributedScience/Distributed-CellProfiler#158]
If your dockers run out of memory jobs fail silently. It's annoying.
Our per-instance logs do regularly print instance metrics that include memory in use and memory available metrics. However, parsing them is annoying.

It would be nice if we could add in a regular print statement into the logs that is human readable and reports memory metrics so that one could more easily determine if memory issues are bonking jobs by browsing logs.
Perhaps also include `WARNING` in the statement if it's above a certain threshold so that a CloudWatch dashboard widget could easily report it?

**Comment by bethac07** [comment]
We could also explore whether we want to do the actual agent installation as part of DCP - I doubt it, but if it's optional maybe not a terrible idea
