### ISSUE TITLE
Spot Fleet Request Configuration Invalid

### ISSUE THREAD

**Issue by znavidi** [DistributedScience/Distributed-CellProfiler#178]
Hi,

Thanks for your amazing software! I have been trying to install and run distributed cellprofiler for a few weeks and after preparing required metadata and updating config files based on the provided guideline (replaced  Line 12 of lambda_function.py with my bucket name, updated config.py, updated files/exampleJob.json, updated files/exampleFleet_us-east-1.json), I get the following **spotFleetRequestConfigurationInvalid** error when running step 3 (step 0 to step 2 seems to be completed without error):

<img width="1287" alt="Screenshot 2024-07-30 at 5 14 50 PM" src="https://github.com/user-attachments/assets/da2585d3-91a9-4567-a580-688ae5aae4e6">

and the following are the text inside the files/cellpainting-cp-analysisSpotFleetRequestId.json that it creates:

<img width="1082" alt="Screenshot 2024-07-23 at 10 22 18 AM" src="https://github.com/user-attachments/assets/afc84dae-3219-4bd2-8e72-141cc47cbe5f">

The updated .json files are attached, and the below are the setting for my config.py file. Since the above error is general, I would highly appreciate if someone can provide a guideline or clue about where to fix or look at to make it works. Also, pls let me know if it helps to provide screenshots from my aws console setting.

Thanks a lot,

# config.py

## Constants (User configurable)

APP_NAME = 'cellpainting-cp-analysis'                # Used to generate derivative names unique to the application.
LOG_GROUP_NAME = APP_NAME

## DOCKER REGISTRY INFORMATION:
DOCKERHUB_TAG = 'cellprofiler/distributed-cellprofiler:2.0.0_4.2.4'

## AWS GENERAL SETTINGS:
AWS_REGION = 'us-east-1'
AWS_PROFILE = 'default'                 # The same profile used by your AWS CLI installation
SSH_KEY_NAME = 'ec2-key1.pem'      # Expected to be in ~/.ssh
AWS_BUCKET = 'cellpainting-cp-analysis'         # Bucket to use for logging
SOURCE_BUCKET = 'cellpainting-cp-analysis'           # Bucket to download image files from
WORKSPACE_BUCKET = 'cellpainting-cp-analysis'        # Bucket to download non-image files from
DESTINATION_BUCKET = 'cellpainting-cp-analysis'      # Bucket to upload files to
UPLOAD_FLAGS = ''                       # Any flags needed for upload to destination bucket

## EC2 AND ECS INFORMATION:
ECS_CLUSTER = 'default'
CLUSTER_MACHINES = 3
TASKS_PER_MACHINE = 1
MACHINE_TYPE = ['c5.xlarge']
MACHINE_PRICE = 0.20
EBS_VOL_SIZE = 30                       # In GB.  Minimum allowed is 22.
DOWNLOAD_FILES = 'False'

## DOCKER INSTANCE RUNNING ENVIRONMENT:
DOCKER_CORES = 4                        # Number of CellProfiler processes to run inside a docker container
CPU_SHARES = DOCKER_CORES * 1024        # ECS computing units assigned to each docker container (1024 units = 1 core)
MEMORY = 15000                           # Memory assigned to the docker container in MB
SECONDS_TO_START = 3*60                 # Wait before the next CP process is initiated to avoid memory collisions

## SQS QUEUE INFORMATION:
SQS_QUEUE_NAME = APP_NAME + 'Queue'
SQS_MESSAGE_VISIBILITY = 1*60           # Timeout (secs) for messages in flight (average time to be processed)
SQS_DEAD_LETTER_QUEUE = 'user_DeadMessages'
JOB_RETRIES = 3            # Number of times to retry a job before sending it to DEAD_LETTER_QUEUE

## MONITORING
AUTO_MONITOR = 'True'

## CLOUDWATCH DASHBOARD CREATION
CREATE_DASHBOARD = 'True'           # Create a dashboard in Cloudwatch for run
CLEAN_DASHBOARD = 'True'            # Automatically remove dashboard at end of run with Monitor

## REDUNDANCY CHECKS
CHECK_IF_DONE_BOOL = 'False'  #True or False- should it check if there are a certain number of non-empty files and delete the job if yes?
EXPECTED_NUMBER_FILES = 7    #What is the number of files that trigger skipping a job?
MIN_FILE_SIZE_BYTES = 1      #What is the minimal number of bytes an object should be to "count"?
NECESSARY_STRING = ''        #Is there any string that should be in the file name to "count"?

## CELLPROFILER SETTINGS
ALWAYS_CONTINUE = 'False'     # Whether or not to run CellProfiler with the --always-continue flag, which will keep CellProfiler from crashing if it errors

## PLUGINS
USE_PLUGINS = 'False'          # True to use any plugin from CellProfiler-plugins repo
UPDATE_PLUGINS = 'False'       # True to download updates from CellProfiler-plugins repo
PLUGINS_COMMIT = 'False'       # What commit or version tag do you want to check out? If not, set to False.
INSTALL_REQUIREMENTS = 'False' # True to install REQUIREMENTS defined below. Requirements should have all plugin dependencies.
REQUIREMENTS = ''       # Flag to use with install (current) or path within the CellProfiler-plugins repo to a requirements file (deprecated).
 

[exampleJob.json](https://github.com/user-attachments/files/16447231/exampleJob.json)
[exampleFleet_us-east-1.json](https://github.com/user-attachments/files/16447232/exampleFleet_us-east-1.json)

**Comment by ErinWeisbart** [comment]
I have just added a new page to our Distributed-CellProfiler documentation on [Troubleshooting problems with startCluster](https://distributedscience.github.io/Distributed-CellProfiler/troubleshooting_start_cluster.html).

The error message you were getting (Your spot fleet request is causing an error and is now being cancelled.  Please check your configuration and try again. spotFleetRequestConfigurationInvalid : c5.xlarge, ami-0f161e6034a6262d8, Linux/UNIX: Value) indicates that this is an issue with your `IamInstanceProfile` - either a misconfiguration in your Fleet File or a problem with permissions for the profile itself. Both are now addressed in the new documentation page.

Additionally, you should now be able to simply run `setup_AWS.py` to correct fix the IamInstanceProfile permissions issue.

(FYI @emiglietta)

**Comment by znavidi** [comment]
Thanks so much Erin. The documentation was super helpful and resolved my issue in running step 3 successfully.

Best
