### ISSUE TITLE
Make a public data set, pipeline, CSV, job file, etc

### ISSUE THREAD

**Issue by bethac07** [DistributedScience/Distributed-CellProfiler#75]
Could probably be based on BBBC022/AdvancedSeg.

**Comment by ErinWeisbart** [comment]
create examples folder. point to a public dataset (use cellpainting-gallery). add a pipeline, CSV, job file etc that references the public dataset.

**Comment by ErinWeisbart** [comment]
Added minimal example without needing to point to public datasets so we don't have to worry about confusing permissions in #142 .
