### ISSUE TITLE
Fix docs: s3fs does not like dots in bucket names if your region is not us-east-1

### ISSUE THREAD

**Issue by shntnu** [DistributedScience/Distributed-CellProfiler#84]
Reported by @mwawer

**Comment by mwawer** [comment]
s3fs will fail with:
`s3fs.cpp:s3fs_check_service(3813): unable to connect(host=https://s3.amazonaws.com) - result of checking service`

For details, see:
https://github.com/s3fs-fuse/s3fs-fuse/wiki/FAQ#q-https-connecting-failed-if-bucket-name-includes-dot-

**Comment by ErinWeisbart** [comment]
Added to documentation in #135.
